rails_tudu/config/routes.rb
Tudu::Application.routes.draw do

  
  

  
  controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
  end
  get "/" => "sessions#new"
  
  get "sessions/create"
  get "sessions/destroy"

  get "schedule" => "users#schedule"

  resources :events do
    collection do
      get "in_range"
	  get "today"
    end
  end

  resources :tasks do
    put "finished" => "tasks#finished"
    collection do
      get "in_range"
      get "today"
    end
  end

  get "home" => "home#index"
  get "task" => "home#task"

  resources :users do
    get "schedule"
    collection do
      get "by_email"
    end

    resources :events do
      collection do
        get "in_range"
        get "today"
      end
    end

    resources :tasks do
      put "finished" => "tasks#finished"
      collection do
        get "in_range"
        get "today"
      end
    end

    get "calendar" => "calendar#index"
    resources :recurring_events
  end

  resources :calendar

end

rails_tudu/app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :start_time, :end_time, :name, :description, :priority, :deadline, :duration, :finished
  def self.in_range begin_time, end_time
    Task.where(:start_time => begin_time..end_time)
  end
end

rails_tudu/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user
  before_action :set_task, only: [:show, :edit, :update, :destroy, :finished]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @user.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @user.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @user.tasks.create(task_params)

    respond_to do |format|
      if @task.save
        @user.schedule_tasks
        format.html { redirect_to :back, notice: 'Task was successfully created.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        @user.schedule_tasks

        format.html { redirect_to [@user, @task], notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    @user.schedule_tasks
    respond_to do |format|
      format.html { redirect_to user_tasks_url(@user) }
      format.json { head :no_content }
    end
  end

  # GET /tasks/today
  # GET /tasks/today.json
  def today
    today = Time.now.to_a
	today[0] = today[1] = today[2] = 0
	start_time = Time.local(*today)
	end_time = start_time + 86400 #24 Hours in seconds

    @tasks = @user.tasks
    @tasks = @tasks.where(start_time: (start_time..end_time))

    respond_to do |format|
      format.html { render text: "Unimplemented" }
      format.json { render json: @tasks }
    end	
  end

  # GET /tasks/in_range?start=datetime&end=datetime
  # GET /tasks/in_range.json?start=datetime&end=datetime
  def in_range
    start_time = DateTime.parse params[:start]
    end_time = DateTime.parse params[:end]

    @tasks = @user.tasks
    @tasks = @tasks.where(start_time: (start_time..end_time))

    respond_to do |format|
      format.html { render text: "Unimplemented" }
      format.json { render json: @tasks }
    end
  end

  # PUT /tasks/1/finished
  # PUT /users/1/tasks/1/finished
  # PUT /tasks/1/finished.json
  # PUT /users/1/tasks/1/finished.json
  def finished
    @task.finished = true

    respond_to do |format|
      if @task.save
        format.html { render text: "Unimplemented" }
        format.json { head :no_content }
      else
        format.html { render text: "Unimplemented" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      task_id = params[:id]
      if params[:task_id]
        task_id = params[:task_id]
      end

      @task = Task.find(task_id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @user = current_user
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:start_time, :end_time, :name, :description, :priority, :deadline, :duration, :finished)
    end
end

rails_tudu/app/helpers/tasks_helper.rb
module TasksHelper
end

rails_tudu/app/views/tasks/_form.html.erb
<%= form_for ([@user, @task]) do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
                <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <h4 class="form-group">New Task</h4>
    <div class="form-group">
        <%= label_tag 'Title' %>
        <%= f.text_field :name, :class=>"form-control",:placeholder => "Untitled task" %>
    </div>
    <div class="form-group">
        <%= label_tag 'Deadline' %>
        <%= f.text_field :deadline, :id => "deadline_picker", :class=>"form-control", :placeholder => DateTime.current().to_formatted_s(:custom) %>
    </div>
    <div class="form-group">
        <%= label_tag 'Priority' %>
        <!-- <ul class="segmented-control">
            <button data-value="0"><a>Low</a></button>
            <button data-value="1"><a>Normal</a></button>
            <button data-value="2"><a>High</a></button>
        </ul> -->
        <%= f.select(:priority, options_for_select([['Low', 0], ['Normal', 1], ['High', 2]]) ,{} ,{:class=>"form-control"}) %>
    </div>
    <div class="form-group">
        <%= label_tag 'Time' %><br>
        <div id="duration_slider"></div>
        <%= f.hidden_field :duration, :value => 900, :class=>"form-control" %><br>
        <span id="duration_value">15m</span> 
    </div>
    <div class="form-group">
        <%= label_tag 'Description' %>
        <%= f.text_area :description, :class=>"form-control" %>
    </div>
    <%= f.hidden_field :finished, :value => false %>
    <div class="form-group">
        <%= f.submit "Create Task", :class=>"form-control" %>
    </div>
<% end %>

rails_tudu/app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path(@user) %>

rails_tudu/app/views/tasks/index.html.erb
<table id="tasksTable" class="table table-striped">
  <caption><h2>Tasks</h2></caption>
  <thead>
    <tr>
      <th>#</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Name</th>
      <th>Priority</th>
      <th>Deadline</th>
      <th>Options</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each_with_index do |task, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= task.start_time.to_s(:custom_time) %></td>
        <td><%= task.end_time.to_s(:custom_time) %></td>
        <td class="taskName"><%= task.name %></td>
        <% if task.priority == 2 %>
          <td class="taskPriority"><span class="label label-danger">HIGH</span></td>
        <% elsif task.priority == 1 %>
          <td class="taskPriority"><span class="label label-warning">MED</span></td>
        <% elsif task.priority == 0 %>
          <td class="taskPriority"><span class="label label-success">LOW</span></td>
        <% end %>
        <td><%= task.deadline.to_s(:custom_time) %></td>
        <td><%= link_to 'Details', [@user, task], class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_user_task_path(@user, task), class: "btn btn-default" %></td>
        <td><%= link_to 'Delete', [@user, task], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails_tudu/app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

rails_tudu/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @task.end_time %>
</p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@user, @task) %> |
<%= link_to 'Back', tasks_path(@user) %>