rails_tudu/config/routes.rb
Tudu::Application.routes.draw do

  
  

  
  controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
  end
  get "/" => "sessions#new"
  
  get "sessions/create"
  get "sessions/destroy"

  get "schedule" => "users#schedule"

  resources :events do
    collection do
      get "in_range"
	  get "today"
    end
  end

  resources :tasks do
    put "finished" => "tasks#finished"
    collection do
      get "in_range"
      get "today"
    end
  end

  get "home" => "home#index"
  get "task" => "home#task"

  resources :users do
    get "schedule"
    collection do
      get "by_email"
    end

    resources :events do
      collection do
        get "in_range"
        get "today"
      end
    end

    resources :tasks do
      put "finished" => "tasks#finished"
      collection do
        get "in_range"
        get "today"
      end
    end

    get "calendar" => "calendar#index"
    resources :recurring_events
  end

  resources :calendar

end

rails_tudu/app/views/layouts/_navbar.html.erb
 <header class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar_brand">
        <a href="<%= home_path %>">
          <%= image_tag "logo.png" %>
        </a>
      </span>
    </div>
    <nav class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= current_class?(home_path) %>"><%= link_to 'Home', home_path %></li>
        <li class="<%= current_class?(calendar_index_path) %>"><%= link_to 'Calendar', calendar_index_path %></li>
        <li class="<%= current_class?(events_path) %>"><%= link_to 'Events', events_path %></li>
        <li class="<%= current_class?(tasks_path) %>"><%= link_to 'Tasks', tasks_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Logout",sessions_destroy_path %></li>
      </ul>
    </nav><!--/.nav-collapse -->
  </div>
</header>
<!--NAVBAR END-->

rails_tudu/app/views/layouts/_sidebar.html.erb
<aside id="sidebar" class="well" data-controller="sidebar" data-action>
	<%
		@user = current_user
		@event = @user.events.new
		@task = @user.tasks.new
	%>
	<button type="button" id="switchForm" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-refresh"></i></button>
	<%= render "events/form" %>
	<%= render "tasks/form" %>
</aside>

rails_tudu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tudu</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name,msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<% if (@splash) %>
	<%= yield %>
<% else %>
	<%= render "layouts/navbar" %>
	<%= render "layouts/sidebar" %>
	<div class="pull-left">
		<%= yield %>
	</div>
<% end %>
</body>
</html>