rails_tudu/config/routes.rb
Tudu::Application.routes.draw do

  
  

  
  controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
  end
  get "/" => "sessions#new"
  
  get "sessions/create"
  get "sessions/destroy"

  get "schedule" => "users#schedule"

  resources :events do
    collection do
      get "in_range"
	  get "today"
    end
  end

  resources :tasks do
    put "finished" => "tasks#finished"
    collection do
      get "in_range"
      get "today"
    end
  end

  get "home" => "home#index"
  get "task" => "home#task"

  resources :users do
    get "schedule"
    collection do
      get "by_email"
    end

    resources :events do
      collection do
        get "in_range"
        get "today"
      end
    end

    resources :tasks do
      put "finished" => "tasks#finished"
      collection do
        get "in_range"
        get "today"
      end
    end

    get "calendar" => "calendar#index"
    resources :recurring_events
  end

  resources :calendar

end

rails_tudu/app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :start_time, :end_time, :name, :description
  def self.in_range begin_time, end_time
    Event.where(:start_time => begin_time..end_time)
  end
end

rails_tudu/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = @user.events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = @user.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    session[:return_to] ||= request.referer

    @event = @user.events.create(event_params)

    Rails.logger.debug("event is #{@event}")

    respond_to do |format|
      if @event.save
        format.html { redirect_to :back, notice: 'Event was successfully created.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [@user, @event], notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to user_events_url }
      format.json { head :no_content }
    end
  end

  # GET /events/today
  # GET /events/today.json
  def today
    today = Time.now.to_a
	today[0] = today[1] = today[2] = 0
	start_time = Time.local(*today)
	end_time = start_time + 86400 #24 Hours in seconds
	
	@events = @user.events
    @events = @events.where(start_time: (start_time..end_time))

    respond_to do |format|
      format.html { render text: "Unimplemented" }
      format.json { render json: @events }
    end
	
  end

  # GET /events/in_range?start=datetime&end=datetime
  # GET /events/in_range.json?start=datetime&end=datetime
  def in_range
    start_time = DateTime.parse params[:start]
    end_time = DateTime.parse params[:end]

    @events = @user.events
    @events = @events.where(start_time: (start_time..end_time))

    respond_to do |format|
      format.html { render text: "Unimplemented" }
      format.json { render json: @events }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @user = current_user
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_time, :end_time, :name, :description)
    end
end

rails_tudu/app/helpers/events_helper.rb
module EventsHelper
end

rails_tudu/app/views/events/_form.html.erb
 <%= form_for ([@user, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4 class="form-group">New Event</h4>
  <div class="form-group">
    <%= label_tag 'Title' %>
    <%= f.text_field :name, :class=>"form-control", :placeholder => "Untitled event" %>
  </div>
  <div class="form-group">
    <%= label_tag 'Start' %>
    <%= f.text_field :start_time, :class=>"form-control", :id => "start_time_picker", :placeholder => DateTime.current().to_formatted_s(:custom) %>
  </div>
  <div class="form-group">
    <%= label_tag 'End' %>
    <%= f.text_field :end_time, :class=>"form-control", :id => "end_time_picker", :placeholder => DateTime.current().to_formatted_s(:custom) %>
  </div>
  <div class="form-group">
      <%= label_tag 'Description' %>
      <%= f.text_area :description, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Event", :class=>"btn btn-default" %>
  </div>
<% end %>
</div>

rails_tudu/app/views/events/_show.html.erb
<div id="showEvent">
	<a id="closeEvent">X</a>
	<p>
	  <strong>Start time:</strong>
	  {{start}}
	</p>

	<p>
	  <strong>End time:</strong>
	  {{end}}
	</p>

	<p>
	  <strong>Name:</strong>
	  {{title}}
	</p>

	<p>
	  <strong>Description:</strong>
	  {{description}}
	</p>
</div>

rails_tudu/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @event] %> |
<%= link_to 'Back', events_path %>

rails_tudu/app/views/events/index.html.erb
<table id="eventsTable" class="table table-striped">
  <caption><h2>Events</h2></caption>
  <thead>
    <tr>
      <th>#</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Name</th>
      <th>Options</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each_with_index do |event, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= event.start_time.to_s(:custom_time) %></td>
        <td><%= event.end_time.to_s(:custom_time) %></td>
        <td class="eventName"><%= event.name %></td>
        <td><%= link_to 'Details', [@user, event], class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_event_path(@user, event), class: "btn btn-default" %></td>
        <td><%= link_to 'Delete', [@user, event], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails_tudu/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

rails_tudu/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@user, @event) %> |
<%= link_to 'Back', events_path %>