rails_tudu/config/routes.rb
Tudu::Application.routes.draw do

  
  

  
  controller :sessions do
     get 'login' => :new
     post 'login' => :create
     delete 'logout' => :destroy
  end
  get "/" => "sessions#new"
  
  get "sessions/create"
  get "sessions/destroy"

  get "schedule" => "users#schedule"

  resources :events do
    collection do
      get "in_range"
	  get "today"
    end
  end

  resources :tasks do
    put "finished" => "tasks#finished"
    collection do
      get "in_range"
      get "today"
    end
  end

  get "home" => "home#index"
  get "task" => "home#task"

  resources :users do
    get "schedule"
    collection do
      get "by_email"
    end

    resources :events do
      collection do
        get "in_range"
        get "today"
      end
    end

    resources :tasks do
      put "finished" => "tasks#finished"
      collection do
        get "in_range"
        get "today"
      end
    end

    get "calendar" => "calendar#index"
    resources :recurring_events
  end

  resources :calendar

end

rails_tudu/app/models/recurring_event.rb
class RecurringEvent < ActiveRecord::Base
end

rails_tudu/app/controllers/recurring_events_controller.rb
class RecurringEventsController < ApplicationController
  before_action :set_recurring_event, only: [:show, :edit, :update, :destroy]

  # GET /recurring_events
  # GET /recurring_events.json
  def index
    @recurring_events = RecurringEvent.all
  end

  # GET /recurring_events/1
  # GET /recurring_events/1.json
  def show
  end

  # GET /recurring_events/new
  def new
    @recurring_event = RecurringEvent.new
  end

  # GET /recurring_events/1/edit
  def edit
  end

  # POST /recurring_events
  # POST /recurring_events.json
  def create
    @recurring_event = RecurringEvent.new(recurring_event_params)

    respond_to do |format|
      if @recurring_event.save
        format.html { redirect_to @recurring_event, notice: 'Recurring event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recurring_event }
      else
        format.html { render action: 'new' }
        format.json { render json: @recurring_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recurring_events/1
  # PATCH/PUT /recurring_events/1.json
  def update
    respond_to do |format|
      if @recurring_event.update(recurring_event_params)
        format.html { redirect_to @recurring_event, notice: 'Recurring event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recurring_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recurring_events/1
  # DELETE /recurring_events/1.json
  def destroy
    @recurring_event.destroy
    respond_to do |format|
      format.html { redirect_to recurring_events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurring_event
      @recurring_event = RecurringEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recurring_event_params
      params.require(:recurring_event).permit(:recurring_start_time, :recurring_end_time, :start_time, :end_time, :every_monday, :every_tuesday, :every_wednesday, :every_thursday, :every_friday, :every_saturday, :every_sunday, :weeks_between, :name, :description)
    end
end

rails_tudu/app/helpers/recurring_events_helper.rb
module RecurringEventsHelper
end

rails_tudu/app/views/recurring_events/_form.html.erb
<%= form_for(@recurring_event) do |f| %>
  <% if @recurring_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recurring_event.errors.count, "error") %> prohibited this recurring_event from being saved:</h2>

      <ul>
      <% @recurring_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recurring_start_time %><br>
    <%= f.datetime_select :recurring_start_time %>
  </div>
  <div class="field">
    <%= f.label :recurring_end_time %><br>
    <%= f.datetime_select :recurring_end_time %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.time_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :every_monday %><br>
    <%= f.check_box :every_monday %>
  </div>
  <div class="field">
    <%= f.label :every_tuesday %><br>
    <%= f.check_box :every_tuesday %>
  </div>
  <div class="field">
    <%= f.label :every_wednesday %><br>
    <%= f.check_box :every_wednesday %>
  </div>
  <div class="field">
    <%= f.label :every_thursday %><br>
    <%= f.check_box :every_thursday %>
  </div>
  <div class="field">
    <%= f.label :every_friday %><br>
    <%= f.check_box :every_friday %>
  </div>
  <div class="field">
    <%= f.label :every_saturday %><br>
    <%= f.check_box :every_saturday %>
  </div>
  <div class="field">
    <%= f.label :every_sunday %><br>
    <%= f.check_box :every_sunday %>
  </div>
  <div class="field">
    <%= f.label :weeks_between %><br>
    <%= f.number_field :weeks_between %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_tudu/app/views/recurring_events/edit.html.erb
<h1>Editing recurring_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @recurring_event %> |
<%= link_to 'Back', recurring_events_path %>

rails_tudu/app/views/recurring_events/index.html.erb
<h1>Listing recurring_events</h1>

<table>
  <thead>
    <tr>
      <th>Recurring start time</th>
      <th>Recurring end time</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Every monday</th>
      <th>Every tuesday</th>
      <th>Every wednesday</th>
      <th>Every thursday</th>
      <th>Every friday</th>
      <th>Every saturday</th>
      <th>Every sunday</th>
      <th>Weeks between</th>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recurring_events.each do |recurring_event| %>
      <tr>
        <td><%= recurring_event.recurring_start_time %></td>
        <td><%= recurring_event.recurring_end_time %></td>
        <td><%= recurring_event.start_time %></td>
        <td><%= recurring_event.end_time %></td>
        <td><%= recurring_event.every_monday %></td>
        <td><%= recurring_event.every_tuesday %></td>
        <td><%= recurring_event.every_wednesday %></td>
        <td><%= recurring_event.every_thursday %></td>
        <td><%= recurring_event.every_friday %></td>
        <td><%= recurring_event.every_saturday %></td>
        <td><%= recurring_event.every_sunday %></td>
        <td><%= recurring_event.weeks_between %></td>
        <td><%= recurring_event.name %></td>
        <td><%= recurring_event.description %></td>
        <td><%= link_to 'Show', recurring_event %></td>
        <td><%= link_to 'Edit', edit_recurring_event_path(recurring_event) %></td>
        <td><%= link_to 'Destroy', recurring_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recurring event', new_recurring_event_path %>

rails_tudu/app/views/recurring_events/new.html.erb
<h1>New recurring_event</h1>

<%= render 'form' %>

<%= link_to 'Back', recurring_events_path %>

rails_tudu/app/views/recurring_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recurring start time:</strong>
  <%= @recurring_event.recurring_start_time %>
</p>

<p>
  <strong>Recurring end time:</strong>
  <%= @recurring_event.recurring_end_time %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @recurring_event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @recurring_event.end_time %>
</p>

<p>
  <strong>Every monday:</strong>
  <%= @recurring_event.every_monday %>
</p>

<p>
  <strong>Every tuesday:</strong>
  <%= @recurring_event.every_tuesday %>
</p>

<p>
  <strong>Every wednesday:</strong>
  <%= @recurring_event.every_wednesday %>
</p>

<p>
  <strong>Every thursday:</strong>
  <%= @recurring_event.every_thursday %>
</p>

<p>
  <strong>Every friday:</strong>
  <%= @recurring_event.every_friday %>
</p>

<p>
  <strong>Every saturday:</strong>
  <%= @recurring_event.every_saturday %>
</p>

<p>
  <strong>Every sunday:</strong>
  <%= @recurring_event.every_sunday %>
</p>

<p>
  <strong>Weeks between:</strong>
  <%= @recurring_event.weeks_between %>
</p>

<p>
  <strong>Name:</strong>
  <%= @recurring_event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recurring_event.description %>
</p>

<%= link_to 'Edit', edit_recurring_event_path(@recurring_event) %> |
<%= link_to 'Back', recurring_events_path %>